services:
  mysql:
    image: mysql:8.0.22
    platform: linux/amd64
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=whos_watching
      - secure-file-priv=/
