# syntax=docker/dockerfile:1

##
## Build
##
FROM node:18-alpine as build

WORKDIR /app

COPY ui/ ./

RUN npm install

RUN npm run build 

# Deploy
FROM nginx:alpine

COPY --from=build /app/build/ /usr/share/nginx/html
RUN ["mv", "/etc/nginx/conf.d/default.conf", "/etc/nginx/conf.d/default.conf.old"]
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]
